### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by alpimany**

### CODE REVIEW

**Comment by xrokz** [comment]
The server file uses config.url so....

**Comment by alpimany** [comment]
[server.js line 8](https://github.com/xrokz/WebChat/blob/a9393993671a655276db494f98d0363ff132e01a/server.js#L8)
```js
const config = require("./config/db.json")

const uri = config.uri; // <---

mongoose.connect(uri, {
  useNewUrlParser: true,
  useUnifiedTopology: true
});
```

**Comment by xrokz** [comment]
commit it

**Comment by alpimany** [comment]
it's committed, just merge my pull request.

**Pull request merged**
